### ISSUE TITLE
‘{{ TEXT }} TEXT’ turns into {{ TEXT }} TEXT after sorted

### ISSUE THREAD

**Issue by SilongXu** [pascalre/vscode-yaml-sort#154] opened 2023-08-31 04:05 UTC
Before: 
<img width="156" alt="16113adf6d28ceb3f72ce4f5a5300f5" src="https://github.com/pascalre/vscode-yaml-sort/assets/58178821/6be650d7-5058-48f3-857c-1f391adfd52e">

After: 
<img width="135" alt="48554fc55876e2671f6a0609c6d1d5c" src="https://github.com/pascalre/vscode-yaml-sort/assets/58178821/43860ed3-6042-461a-bb4a-688b5b1d06b7">

I wanna keep this format: '{{ TEXT }} TEXT'

**Comment by blubberdiblub** [comment] 2023-10-29 07:00
Related to or duplicate of #142

**Comment by pascalre** [comment] 2024-01-21 22:10
@SilongXu will be fixed in the next release

**Closed by pascalre** 2024-01-21 22:10 UTC
Labels: bug
